### ISSUE TITLE
CmdType parsing enhancements

### ISSUE THREAD

**Issue by pawelsky** [CunningLogic/dumlPrinter#1]
Hi, nice tool, but you may want to add some corrections to the CmdType parsing:
- add the encryption type (defined by lower 4 bits)
- separate request/response bit (the highest one) from the ACK type (next 2 bits).

See the Wireshark LUA dissector, that I've recently updated: https://github.com/o-gs/dji-firmware-tools/blob/master/comm_dissector/wireshark/dji-mavic.lua

**Comment by CunningLogic** [comment]
Hi,
Encryption parsing is intentionally not handled, I actually wipe out those bits on purpose.

I will need to look into the request/response bit, and I will update on that thank you
